export * from "./home";
export * from "./korzinka";
export * from "./pustaya";
export * from "./notFound";
export * from "./singlePizza";
export * from "./Pay";
export * from "./singUp";
export * from "./singIn";
export * from "./addNewPizza";
